# arkade_version: '0.11.37'
# arkade_os: 'linux'
# arkade_cpu_arch: 'amd64'
# # force_reinstall_arkade: ''

##########################################
### PKI CA Cert
pesto_pki_ca_name: "Pestoplatform-RootCA"
pesto_pki_ca_fqdn: 'pestoplaform-ca.pesto.io'
pesto_pki_ca_validity_in_days: 1826
pesto_pki_ca_passphrase: 'In that pleasant district of merry England which is watered by the river Don, there extended in ancient times a large forest, covering the greater part of the beautiful hills and valleys which lie between Sheffield and the pleasant town of Doncaster.'

##########################################
### Open BAO Cert
pesto_openbao_cert_validity_in_days: 730
pesto_openbao_fqdn: 'openbao.pesto.io'
pesto_openbao_ip_address_1: 192.168.1.16
pesto_openbao_ip_address_2: 192.168.1.17


##########################################
### Room Zero

# desired_room_zero_home: "~/.room.zero"
pesto_room_zero_home: "~/.room.zero"

# desired_room_zero_bind_addr: "192.168.1.16"
pesto_room_zero_bind_addr: "192.168.1.16"

# desired_pesto_room_zero_non_routed_ip_addr
pesto_room_zero_non_routed_ip_addr: '172.20.0.5'

# desired_knd_net_name: "kind"
pesto_knd_net_name: "kind"

# desired_openbao_fqdn
# pesto_openbao_fqdn: "openbao.pesto.io"

# desired_openbao_fqdn: "openbao.pesto.io"
pesto_room_zero_container_name: "room_zero"

# desired_room_zero_container_name: "room_zero"
pesto_openbao_tls_cert_path: "{{ room_zero_home }}/openbao.pesto.io.cert"

# desired_openbao_tls_cert_path: "{{ room_zero_home }}/openbao.pesto.io.cert"
pesto_openbao_tls_cert_key_path: "{{ room_zero_home }}/openbao.pesto.io.key"

# desired_openbao_tls_cert_key_path: "{{ room_zero_home }}/openbao.pesto.io.key"
force_recreate_room_zero: true

# desired_docker_compose_file_name
# pesto_room_zero_docker_compose_file_name: "docker-compose.room.zero.yaml"