---
- name: Provision OpenBAO
  hosts: [k8s-cluster]
  any_errors_fatal: true
  gather_facts: false
  roles:
    # ---
    # (Re-)Install Arkade
    - role: arkade
      force_reinstall_arkade: true
      arkade_version: '0.11.38'
      arkade_os: 'linux'
      arkade_cpu_arch: 'amd64'