---
##########################################
##########################################
##########################################
### Check role provided params
# --- 
# desired_openbao_ops_home
- name: "Set fact desired OpenBAO Ops Home location"
  ansible.builtin.set_fact:
    desired_openbao_ops_home: "{{ openbao_ops_home | default('/opt/pesto/openbao') }}"

- name: "Print fact desired OpenBAO Ops Home location"
  ansible.builtin.debug:
    var: desired_openbao_ops_home
    verbosity: 2
# --- 
# desired_openbao_fqdn
- name: "Set fact desired OpenBAO FQDN"
  ansible.builtin.set_fact:
    desired_openbao_fqdn: "{{ pesto_openbao_fqdn | default('openbao.pesto.io') }}"

- name: "Print fact desired OpenBAO FQDN"
  ansible.builtin.debug:
    var: desired_openbao_fqdn
    verbosity: 2

# --- 
# desired_openbao_k8s_ns
- name: "Set fact desired OpenBAO Kubernetes namespace"
  ansible.builtin.set_fact:
    desired_openbao_k8s_ns: "{{ pesto_openbao_k8s_ns | default('openbao.pesto.io') }}"

- name: "Print fact desired OpenBAO Kubernetes namespace"
  ansible.builtin.debug:
    var: desired_openbao_k8s_ns
    verbosity: 2

# --- 
# desired_openbao_provisioning_name
- name: "Set fact desired OpenBAO Provisioning Name"
  ansible.builtin.set_fact:
    desired_openbao_provisioning_name: "{{ pesto_openbao_provisioning_name | default('openbao.pesto.io') }}"

- name: "Print fact desired OpenBAO Provisioning Name"
  ansible.builtin.debug:
    var: desired_openbao_provisioning_name
    verbosity: 2

# --- 
# desired_openbao_helm_repo_name
- name: "Set fact desired OpenBAO Helm Repo Name"
  ansible.builtin.set_fact:
    desired_openbao_helm_repo_name: "{{ pesto_openbao_helm_repo_name | default('openbao/openbao') }}"

- name: "Print fact desired OpenBAO Helm Repo Name"
  ansible.builtin.debug:
    var: desired_openbao_helm_repo_name
    verbosity: 2

# --- 
# desired_openbao_helm_repo_url
- name: "Set fact desired OpenBAO Helm Repo URL"
  ansible.builtin.set_fact:
    desired_openbao_helm_repo_url: "{{ pesto_openbao_helm_repo_url | default('https://openbao.github.io/openbao-helm') }}"

- name: "Print fact desired OpenBAO Helm Repo URL"
  ansible.builtin.debug:
    var: desired_openbao_helm_repo_url
    verbosity: 2

# --- 
# desired_helm_chart_version
- name: "Set fact desired OpenBAO Helm Chart Version"
  ansible.builtin.set_fact:
    desired_helm_chart_version: "{{ pesto_helm_chart_version | default('0.12.0') }}"

- name: "Print fact desired OpenBAO Helm Chart Version"
  ansible.builtin.debug:
    var: desired_helm_chart_version
    verbosity: 2

##########################################
##########################################
##########################################
### Create OpenBAO Ops Home folder
### 
- name: "Create OpenBAO Ops Home folder"
  become: true
  ansible.builtin.shell: |
    export DESIRED_OPENBAO_OPS_HOME='{{ desired_openbao_ops_home }}'
    echo " DESIRED_OPENBAO_OPS_HOME = [${DESIRED_OPENBAO_OPS_HOME}] "
    if [ -d ${DESIRED_OPENBAO_OPS_HOME} ]; then
      rm -fr ${DESIRED_OPENBAO_OPS_HOME}
    fi;
    mkdir -p ${DESIRED_OPENBAO_OPS_HOME}
    chown -R {{ operator_lx_user_name }}:{{ operator_lx_user_name }} ${DESIRED_OPENBAO_OPS_HOME}
    ls -alh ${DESIRED_OPENBAO_OPS_HOME}
  register: create_openbao_ops_home_folder_ouput
  when: 
    - running_os == "debian12"
- name: "Print stdout of Create OpenBAO Ops Home folder"
  ansible.builtin.debug:
    var: create_openbao_ops_home_folder_ouput
    verbosity: 2
  when: 
    - running_os == "debian12"
##########################################
##########################################
##########################################
### Provision OpenBAO
### 
- name: "Provision OpenBAO"
  # become: true
  ansible.builtin.shell: |
    export DESIRED_OPENBAO_OPS_HOME='{{ desired_openbao_ops_home }}'
    echo " DESIRED_OPENBAO_OPS_HOME = [${DESIRED_OPENBAO_OPS_HOME}] "
    ls -alh ${DESIRED_OPENBAO_OPS_HOME}
    cd ${DESIRED_OPENBAO_OPS_HOME}
    export DESIRED_OPENBAO_K8S_NS='{{ desired_openbao_k8s_ns | default('pesto_openbao') }}'
    echo " DESIRED_OPENBAO_K8S_NS = [${DESIRED_OPENBAO_K8S_NS}] "
    export DESIRED_OPENBAO_FQDN='{{ desired_openbao_fqdn }}'
    echo " DESIRED_OPENBAO_FQDN = [${DESIRED_OPENBAO_FQDN}] "
    export DESIRED_OPENBAO_PROVISIONING_NAME='{{ desired_openbao_provisioning_name }}'
    echo " DESIRED_OPENBAO_PROVISIONING_NAME = [${DESIRED_OPENBAO_PROVISIONING_NAME}] "
    export DESIRED_OPENBAO_HELM_RELEASE_NAME="${DESIRED_OPENBAO_PROVISIONING_NAME}"
    echo " DESIRED_OPENBAO_HELM_RELEASE_NAME = [${DESIRED_OPENBAO_HELM_RELEASE_NAME}] "
    export DESIRED_OPENBAO_K8S_SERVICE_NAME="${DESIRED_OPENBAO_PROVISIONING_NAME}"
    echo " DESIRED_OPENBAO_K8S_SERVICE_NAME = [${DESIRED_OPENBAO_K8S_SERVICE_NAME}] "
    export DESIRED_OPENBAO_HELM_REPO_NAME='{{ desired_openbao_helm_repo_name | default('openbao/openbao') }}'
    echo " DESIRED_OPENBAO_HELM_REPO_NAME = [${DESIRED_OPENBAO_HELM_REPO_NAME}] "
    export DESIRED_OPENBAO_HELM_REPO_URL='{{ desired_openbao_helm_repo_url | default('https://openbao.github.io/openbao-helm') }}'
    echo " DESIRED_OPENBAO_HELM_REPO_URL = [${DESIRED_OPENBAO_HELM_REPO_NAME}] "
    
    export DESIRED_HELM_CHART_VERSION='{{ desired_helm_chart_version | default('0.12.0') }}'
    echo " DESIRED_HELM_CHART_VERSION = [${DESIRED_HELM_CHART_VERSION}] "
    
# https://openbao.org/docs/platform/k8s/helm/

helm repo add openbao https://openbao.github.io/openbao-helm

helm search repo openbao/openbao -l

export DESIRED_CHART_VERSION=${DESIRED_CHART_VERSION:-'0.12.0'}

export HELM_KUBECONTEXT=${HELM_KUBECONTEXT:-'kind-openbao-cluster'}


export HELM_RELEASE_NAME=${HELM_RELEASE_NAME:-'pesto-openbao'}
export K8S_NS=${K8S_NS:-'pesto-openbao'}


helm install ${HELM_RELEASE_NAME} openbao/openbao --version ${DESIRED_CHART_VERSION} \
     --namespace ${K8S_NS} \
     --create-namespace \
     --set server.dev.enabled=true


# helm delete ${HELM_RELEASE_NAME}

helm get manifest -n ${K8S_NS} ${HELM_RELEASE_NAME}
helm status -n ${K8S_NS} ${HELM_RELEASE_NAME}

kubectl --context kind-openbao-cluster get all -n pesto-openbao

  register: provision_openbao_ouput
  when: 
    - running_os == "debian12"
- name: "Print stdout of Provision Ingress Controller - NGINX"
  ansible.builtin.debug:
    var: provision_openbao_ouput
    verbosity: 2
  when: 
    - running_os == "debian12"


##########################################
##########################################
##########################################
### Provision OpenBAO Ingress Rule (NGINX)
### 
- name: "Provision OpenBAO Ingress Rule - NGINX"
  # become: true
  ansible.builtin.shell: |
    export DESIRED_OPENBAO_OPS_HOME='{{ desired_openbao_ops_home }}'
    echo " DESIRED_OPENBAO_OPS_HOME = [${DESIRED_OPENBAO_OPS_HOME}] "
    ls -alh ${DESIRED_OPENBAO_OPS_HOME}
    cd ${DESIRED_OPENBAO_OPS_HOME}
    export DESIRED_OPENBAO_K8S_NS='{{ desired_openbao_k8s_ns | default('pesto_openbao') }}'
    echo " DESIRED_OPENBAO_K8S_NS = [${DESIRED_OPENBAO_K8S_NS}] "
    export DESIRED_OPENBAO_FQDN='{{ desired_openbao_fqdn }}'
    echo " DESIRED_OPENBAO_FQDN = [${DESIRED_OPENBAO_FQDN}] "
    export DESIRED_OPENBAO_PROVISIONING_NAME='{{ desired_openbao_provisioning_name }}'
    echo " DESIRED_OPENBAO_PROVISIONING_NAME = [${DESIRED_OPENBAO_PROVISIONING_NAME}] "
    export DESIRED_OPENBAO_HELM_RELEASE_NAME="${DESIRED_OPENBAO_PROVISIONING_NAME}"
    echo " DESIRED_OPENBAO_HELM_RELEASE_NAME = [${DESIRED_OPENBAO_HELM_RELEASE_NAME}] "
    export DESIRED_OPENBAO_K8S_SERVICE_NAME="${DESIRED_OPENBAO_PROVISIONING_NAME}"
    echo " DESIRED_OPENBAO_K8S_SERVICE_NAME = [${DESIRED_OPENBAO_K8S_SERVICE_NAME}] "
    export DESIRED_OPENBAO_HELM_REPO_NAME='{{ desired_openbao_helm_repo_name | default('openbao/openbao') }}'
    echo " DESIRED_OPENBAO_HELM_REPO_NAME = [${DESIRED_OPENBAO_HELM_REPO_NAME}] "
    export DESIRED_OPENBAO_HELM_REPO_URL='{{ desired_openbao_helm_repo_url | default('https://openbao.github.io/openbao-helm') }}'
    echo " DESIRED_OPENBAO_HELM_REPO_URL = [${DESIRED_OPENBAO_HELM_REPO_NAME}] "
    
    export DESIRED_HELM_CHART_VERSION='{{ desired_helm_chart_version | default('0.12.0') }}'
    echo " DESIRED_HELM_CHART_VERSION = [${DESIRED_HELM_CHART_VERSION}] "
    
    cat <<EOF >./openbao-ingress-rule.yaml
    ---
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: openbao-ingress
      namespace: ${DESIRED_OPENBAO_K8S_NS}
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
    spec:
      ingressClassName: nginx
      rules:
      - host: "${DESIRED_OPENBAO_FQDN}"
        http:
          paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ${DESIRED_OPENBAO_K8S_SERVICE_NAME}
                port:
                  number: 8200
    EOF
    kubectl apply -f ./openbao-ingress-rule.yaml
  register: provision_openbao_ingress_rule_ouput
  when: 
    - running_os == "debian12"
- name: "Print stdout of Provision OpenBAO Ingress Rule - NGINX"
  ansible.builtin.debug:
    var: provision_openbao_ingress_rule_ouput
    verbosity: 2
  when: 
    - running_os == "debian12"

